### ISSUE TITLE
Support for Rackconnect version 3

### ISSUE THREAD

**Issue by srirajan** [chef/knife-rackspace#102]
knife-rackspace added --rackconnect-wait  which causes it to wait until the Rackconnect automation setup is complete before bootstrapping chef.

Original PR: https://github.com/chef/knife-rackspace/pull/35 

With v3, the process has completely changed. Cloud servers in v3 do not get a public IP by default and you need to make an separate Rackconnect API call for a public IP. So essentially Knife-rackspace needs to be tweaked to add those additional calls and then wait before bootstrapping.  We will need to retain the v2 functionality as well for backwards compatibility.  So something like --rackconnect-v3-wait which makes the call and waits till the IP is provisioned. 'accessIPv4' is still correctly populated as before and so that is the right public IP to use.

More about the Rackconnect API can be found here.
http://www.rackspace.com/knowledge_center/article/getting-started-with-the-rackconnect-v30-api#section3_add_public_IP_address_API

Let me know if you need more details.

Thanks

**Comment by mdarby** [comment]
This will be live in 0.10.1
