### ISSUE TITLE
--retry-ssh-limit command line option isn't used

### ISSUE THREAD

**Issue by linxit** [chef/knife-rackspace#120]
Running knife rackspace server create:

This was only a problem with the Ubuntu 14.04 image, but it failed every time to ssh without trying more than once.

I looked at the code and found that in the tcp_test_ssh function was trying to read it from Chef::Config[:knife][:retry_ssh_limit] rather than config[:retry_ssh_limit], so limit was always 0 and the rescue code was never run.

I worked round it by setting the value in knife.rb, but this is definitely a bug.

**Comment by benLogN** [comment]
Should be fixed by https://github.com/chef/knife-rackspace/pull/122.
