### ISSUE TITLE
knife rackspace server create issue with creating compute* and memory* server

### ISSUE THREAD

**Issue by m89an32d7w** [chef/knife-rackspace#121]
Hi guys,

I'm trying to create a new cloud server using knife-rackspace 0.11.0 with the following command:

knife rackspace server create --bootstrap-network private --rackconnect-wait --run-list recipe[new-web-node::default] --rackspace-metadata "{\"RackConnectPublicIP\" : \"x.x.x.x\"}" --server-name webtest --node-name webtest --flavor compute1-15 --image c25f1ae0-30b3-4012-8ca6-5ecfcf05c965

getting this error:
ERROR: Fog::Compute::RackspaceV2::BadRequest: [HTTP 400 | req-ce8beb1b-e329-47e0-928c-9cdc1a384f42] Invalid imageRef provided. -

I tried with -I instead of --image same result. also tested different image ID's with no success. Tried adding -B option without parameter (I don't have a block storage boot ID yet) but still getting same error. 

From what I understand using the -I flag should be enough. Reading from #95 
"Since this option is explicitly for preexisting boot volumes, this
commit also makes the -I flag smart enough to know whether it should
create the server passing the :image_id configuration option or whether
it should create the server passing the :boot_image_id option."

my chef version is: chef-11.10.4-1.el6.x86_64

I have no fancy config option in knife.rb btw

**Comment by m89an32d7w** [comment]
output from same command using -VV maybe it helps
DEBUG: version  (config)
DEBUG: version v2 (cli)
DEBUG: rackspace_api_key xxxxxx
DEBUG: rackspace_username
DEBUG: rackspace_api_username xxxxxx
DEBUG: rackspace_auth_url
DEBUG: rackspace_auth_url
DEBUG: rackspace_auth_url https://identity.api.rackspacecloud.com/v2.0 (using)
DEBUG: rackspace_region ord
DEBUG: rackspace_region ord
DEBUG: rackspace v2
DEBUG: https_proxy <not specified> (config)
DEBUG: http_proxy <not specified> (config)
DEBUG: using proxy <none> (config)
DEBUG: ssl_verify_peer <not specified> (config)
DEBUG: version  (config)
DEBUG: version v2 (cli)
DEBUG: rackspace_api_key xxxxx
DEBUG: rackspace_username
DEBUG: rackspace_api_username xxxxx
DEBUG: rackspace_auth_url
DEBUG: rackspace_auth_url
DEBUG: rackspace_auth_url https://identity.api.rackspacecloud.com/v2.0 (using)
DEBUG: rackspace_region ord
DEBUG: rackspace_region ord
DEBUG: rackspace v2
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.33.0/lib/excon/middlewares/expects.rb:10:in `response_call': [HTTP 400 | req-c1c7d4a0-d443-4fd4-907d-4933ec1201dd] Invalid imageRef provided. -  (Fog::Compute::RackspaceV2::BadRequest)
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.33.0/lib/excon/middlewares/response_parser.rb:26:in `response_call'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.33.0/lib/excon/connection.rb:402:in `response'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/excon-0.33.0/lib/excon/connection.rb:272:in `request'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-core-1.22.0/lib/fog/core/connection.rb:56:in `request'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.22.0/lib/fog/rackspace/service.rb:43:in `request'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.22.0/lib/fog/rackspace/compute_v2.rb:165:in `request'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.22.0/lib/fog/rackspace/requests/compute_v2/create_server.rb:80:in `create_server'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.22.0/lib/fog/rackspace/models/compute_v2/server.rb:260:in `create'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/fog-1.22.0/lib/fog/rackspace/models/compute_v2/server.rb:219:in `save'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-rackspace-0.9.1/lib/chef/knife/rackspace_server_create.rb:429:in `run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/knife.rb:491:in `run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/knife.rb:174:in `run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application/knife.rb:135:in `run'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:23:in `load'
        from /usr/bin/knife:23:in `<main>'

**Comment by martinb3** [comment]
@m89an32d7w I don't think the volume support was released in fog until 1.24. You may need to get newer gems. Could you try that and get back to us?

**Comment by tdooner** [comment]
Yeah, your invocation using `-I` is correct. Except that you should make sure to `bundle exec` knife, or remove any older version of the fog gem that you may have lying around.

**Comment by martinb3** [comment]
Closing this since we haven't heard back. Please ping us with a comment if you need any additional assistance. Thanks!

**Comment by m89an32d7w** [comment]
Sorry for delayed response. Had trouble updating fog and knife rackspace on my rpm based centos chef workstation.
Finally I installed latest chef and knife rackspace tool using gem on a new Centos 7 box and was able to test using:

knife rackspace server create --bootstrap-network private --rackconnect-wait --server-name test1 --node-name test1 --flavor compute1-4 --image 6595f1b7-e825-4bd2-addc-c7b1c803a37f

It worked as expected. 
Thanks. Great coding!
