### ISSUE TITLE
Release with breaking changes

### ISSUE THREAD

**Issue by martinb3** [chef/knife-rackspace#129]
We should do a release that includes #127 after testing. It's probably a breaking change.

**Comment by tas50** [comment]
In theory it's not a breaking change. We did the same thing in knife ec2 without issue

**Comment by martinb3** [comment]
Last I looked, the gems had slightly different functionality. I'll confirm before I bump major (if there's no differences, I'll bump minor 👍 )

**Comment by martinb3** [comment]
@jjasghar, I think you originally setup the TravisCI releasing of this gem. It looks like the recent changes removed this part of `.travis.yml`:
```
branches:
  only:
  - master
```

After adding it back, I do see [TravisCI building tags again](https://travis-ci.org/chef/knife-rackspace/builds/170708691), but despite these log lines, I don't see [a deploy](https://rubygems.org/gems/knife-rackspace):
```
  Successfully built RubyGem
  Name: knife-rackspace
  Version: 1.0.0
  File: knife-rackspace-1.0.0.gem

You do not have permission to push to this gem. Ask an owner to add you with: gem owner knife-rackspace --add jjasghar@gmail.com

No stash found.

Done. Your build exited with 0.
```

**Comment by martinb3** [comment]
Just assigning to poke JJ -- I'll drop him an email if this doesn't get his attention 👍

**Comment by jjasghar** [comment]
It seems I was removed from the account, @tas50 is going to put me back and after that deployments should work again.

![image](https://cloud.githubusercontent.com/assets/810824/20327761/16c3bfba-ab54-11e6-8cbe-4e28d89b15ac.png)

**Comment by jjasghar** [comment]
@martinb3 i believe this should be fixed now, please try again, and ping me here if something still isn't working :)

**Comment by martinb3** [comment]
Thanks @jjasghar! I'll give it a try :)

**Comment by martinb3** [comment]
Fixed / works! 👍
