### ISSUE TITLE
Support for new Rackspace instance types and Cloud Block Storage boot volumes

### ISSUE THREAD

**Issue by jpunzel** [chef/knife-rackspace#91]
It looks like Rackspace has changed their cloud server types, adding "Compute" and "Memory" flavors and replacing the performance tiers with "General Purpose" and "I/O". The newer flavors only support using a remote cloud block device as the boot volume. As a result, knife rackspace can't create these, since it seems the API call to create the server now requires the UUID of a cloud block storage volume prepared with an image.

For instance, when I attempt to pass 'compute1-4' as a flavor, I get this error:
ERROR: Fog::Compute::RackspaceV2::ServiceError: [HTTP 403 | req-12b43584-bd39-4a85-9115-4bd42b9ee8f1] Policy doesn't allow compute_flavor:create:image_backed to be performed.

This could also be an issue with Fog, but I'm not entirely sure. It would appear that support was added to Fog for the block_device_mapping attribute on Oct 1st: https://github.com/fog/fog/blob/master/lib/fog/rackspace/requests/compute_v2/create_server.rb

**Comment by jpunzel** [comment]
@tdooner Looks like your PR was denied by the CLA bot. I'd love to see these changes merged.

**Comment by vmihailenco** [comment]
Ping. Any news on this?

**Comment by martinb3** [comment]
#95 appears to be good now, passing the CLA check. I'd love to see it merged! :+1:

**Comment by beeerd** [comment]
Bump, would love to have this!

**Comment by Paladin** [comment]
Just a comment, here:

Device Mapping is still invalid and there needs to be an indication that boot-volume-size is now required (or a workable default plugged in).

**Comment by martinb3** [comment]
@Paladin we should probably open this as a new issue, since this issue is a year old and closed. Could you open an issue and show us the command you're trying to run?
